  <nav class="navbar navbar-bg">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="index.php">Dallas</a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="about-me.php">About Me</a></li>
            <li><a href="past-work.php">Past Work</a></li>
            <li><a href="games.php">Board Games</a></li>
            <li><a href="contact.php">Contact Me</a></li>
          </ul>
        </div>
      </nav>

        <nav class="navbar navbar-bg">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="index.html">Dallas</a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="about-me.html">About Me</a></li>
            <li><a href="past-work.html">Past Work</a></li>
            <li><a href="games.html">Board Games</a></li>
            <li><a href="contact.html">Contact Me</a></li>
          </ul>
        </div>
      </nav>